#!/usr/bin/perl

# NOTE:  the above line must be changed to show the path to the
# Perl interpreter on your system!  Leave the #! as is, but
# the path may have to be changed if yours is different.

#########################################################################
# MakeBook v2.2 3/20/2001						#
# Lets users continually add to an ongoing story that they can then	#
# read immediately on a web page. Can also be used as a guestbook, or   #
# even a form to add comments to different pages. Thanks to Casey who 	#
# gave me the idea for using this as an ongoing story program, and to	#
# David who gave me the idea of using it for a comment form.		#
#									#
# Copyright 1999-2001, Kristina Pfaff-Harris, scripts@tesol.net		#
# All rights reserved.                                             	#
#########################################################################
##### Licensing:							#
#####									#
#####  This program may be used free of charge under the following	#
#####  conditions:							#
#####  									#
#####  1. All instructions and Copyright lines must remain unchanged.	#
#####  									#
#####  2. All pages generated by the program must contain one of the	#
#####     following pieces of HTML code:				#
#####  									#
#####     <font size=-2>MakeBook v2.2 is Copyright 1999-2001		#
#####     Kristina Pfaff-Harris. It can be found at: 			#
#####     <a href="http://www.tesol.net/scripts/">			#
#####     http://www.tesol.net/scripts</a></font>			#
#####  OR:								#
#####     <!-- MakeBook v2.2 Copyright 2001 Kristina Pfaff-Harris -->	#
#####     <!-- Get it at http://www.tesol.net/scripts/         -->	#
##### 									#
#####  3. You may not sell or distribute this program.  You may charge	#
#####     a reasonable fee for installing it for a client as long as	#
#####     you make it clear that you are not the author, and you are	#
#####     not selling the program to them: only charging for installing	#
#####     it. 								#
##### 									#
#####  4. You agree that this program is offered without warranty of	#
#####     any kind, including warranty of fitness for a particular	#
#####     purpose. You further agree that the author and all sites 	#
#####     associated in any way with this program are not liable for	#
#####     any damage or loss incurred as a result of using this program.#
#####									#
#########################################################################
#####                                                                   #
##### IMPORTANT INSTRUCTIONS:                                           #
#####                                                                   #
##### In this program, I have put **CHANGE** in all the places where    #
##### you will need to modify the program to run on your server, so     #
##### that you can easily find all the places where changes are         #
##### necessary.  This program must be chmod 755 or 775 in order to     #
##### work, and the bookfile.html file must be writable by the web	#
##### server, which sometimes means 766. See the README file for more	#
##### details.
#####                                                                   #
#########################################################################
#                                                                       #
# IMPORTANT: If you FTPed this program to your server in "binary" mode, #
# it will NOT work!  If you're not sure, please go back and FTP it      #
# to your server again and make sure you use "ascii" mode.  If you get  #
# "500 Server Error", this is almost always the cause. :)               #
#                                                                       #
# Using the program:                                                    #
# This program requires the file "makebook.cgi" at a minimum in order  	#
# to work.  Please read the README.makebook file for more information. 	#
#                                                                       #
# I hope this program proves useful to you!  If you are having problems,#
# please read all the instructions carefully, and check the FAQ at      #
# http://www.tesol.net/scripts/FAQ/ . If none of this helps, please     #
# contact me (http://www.tesol.net/scriptmail.html) for any bugs or     #
# feedback.                                                             #
#########################################################################
#									#
#            BEGIN SECTION WHERE YOU NEED TO CHANGE THINGS		#
#									#
#  In this next section, there are various things that you need to	#
#  change in order to get the program to work the way you'd like it to.	#
#  Don't worry: each variable has an explanation of what it does and	#
#  what you'll need to do in order to change it.  Be careful of things	#
#  like " and ; and be sure to read the instructions.  If you do this,	#
#  then you should be fine!						#
#									#
#########################################################################

# First of all, let's determine if we want to enable some debugging
# information.  This can be very useful when you are first setting up
# the program, as it can tell you whether or not the program can find
# your "bookfile" and whether it can add entries to it.  If you're
# having problems such as no entries showing up in the bookfile, then
# **CHANGE** this to:
# $debugging = 1;
# To turn debugging off, set $debugging = 0;
# Otherwise, you should leave it as it is.

$debugging = 0;

# $bookfile is the system path to your book file. This lets the 
# program know where to look for the file so that it can add entries to
# it.  This is NOT a URL, and must NOT begin with "http://". It should 
# begin with "/".  **CHANGE** this to the system path to your book file.  
# Sometimes, the setting I have below will work fine for you. (Try it
# and see.)  Otherwise, it should be something like:
# $bookfile = "/home/web/yourlogin/your_web_directory/bookfile.html";
# (On Unix) or something like:
# $bookfile = "c:/inetpub/wwwroot/users/yourlogin/bookfile.html";
# (On NT).  In addition, if you choose "use form for bookfile" below,
# then this will be our "fall back" page if, for some reason, the
# system can't find the correct file.

$bookfile = "/home/superdea/public_html/gerald/bee.txt";

# The URL (web address) to your book file so we can send the 
# user there when they're done entering their text. **CHANGE** 
# this to the URL of your own bookfile.  This *is* a URL, and should 
# begin with "http://".

$bookfile_url = "http://www.deaddeaddead.com/gerald/bee.txt";

# Now, please read this carefully.  You can use MakeBook to write to
# more than one "bookfile."  However, in order for this to work, your
# web server must support sending the "HTTP_REFERER" (Yes, I know, that
# is how it's spelled.)  If you set "$use_form_for_bookfile", Makebook
# will assume that you want to add new entries to the same page as the
# form that calls MakeBook is on. (Please see the example "comments.html"
# file for an example of one of these forms.)  If you want to try this,
# **CHANGE** $use_form_as_bookfile = "no"; to
# $use_form_as_bookfile = "yes";

$use_form_as_bookfile = "no";

# Now, if you selected $use_form_as_bookfile = "yes"; above, you will
# need to tell the program the file path to your various forms. This
# is NOT a URL, but rather a full path to a folder, so it will look
# something like "/home/users/yourlogin/files/" on Unix servers or 
# "c:/inetpub/wwwroot/something/" on NT. **CHANGE** this to
# the path to where you have the pages you'll be using with MakeBook.

$filepath = "/path/to/your/files/";

# $owner is who I want the email sent to for confirmation of
# contributions.  We'll use this later on.  IMPORTANT: Perl version 5 
# requires that all @ signs be preceded by a 
# backslash. (\) **CHANGE** this to your own email address, and make
# sure that the @ sign has a \ in front of it as in the example.

$owner = "gerald\@deaddeaddead.com";

# Define the name of the owner.  **CHANGE** this to your own
# name or appropriate alias. 

$owner_name = "dead gerald";

# Here, we will define our HTML header.  You can monkey about with the
# HTML code here so that it looks like that of your page.  WARNING:
# any " (quotes) or @ ("at" signs) must have a \ (backslash) in front
# of them.  Please be very careful if you modify the HTML code here --
# just one free " and the script will never run.  You can put anything
# you like in between the <!-- Begin HTML Header --> and <!-- End HTML
# Header --> lines.  

$header = "
<!-- Begin HTML Header -->

<html><head><META HTTP-EQUIV=Refresh CONTENT=\"1; URL=http://www.deaddeaddead.com/gerald/index.shtml\"> <title>d e a d b i c y c l e n e e d s g e r a l d b a c k</title></head>
<body bgcolor=\"#FFFFFF\" background=\"http://www.deaddeaddead.com/img/404bg.gif\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"2\" width=\"95%\">
<!-- End HTML Header -->
"; #<-- This quote and semicolon are necessary!  Don't backslash them!


# Now define our HTML footer.  As before, you may change the html
# code, but be careful of " and @ signs. Please leave the copyright
# notice and the address of Scripts for Educators so that other
# people can find and use this program. 

$footer =  "
<!-- Begin HTML Footer -->

</TABLE></body></html>

<!-- End HTML Footer -->
"; #<-- This quote and semicolon are necessary!  Don't backslash them!

# Now, let's enter some options.  The next few lines will let you
# control whether the program emails you with new entries or not,
# whether you'd like new entries to appear at the top of the file or
# the bottom of the file, and whether or not to print the date and
# the user's email address. You may leave these as-is, or **CHANGE**
# them to settings more appropriate to your own needs.
#
# First, $add_to_end_of_file is either "yes" or "no."
# To **CHANGE** this (it starts out as "yes"), just change
# $add_to_end_of_file = "yes"; to
# $add_to_end_of_file = "no";
# That will add the newest entries to the top of the page rather
# than the bottom.  Some people use this feature when they are
# using MakeBook as a guestbook rather than as an ongoing story.

$add_to_end_of_file = "no";


# Next, $show_date_submitted determines whether or not you'd like
# the date the person entered their submission to be shown. Again,
# this can be "yes" or "no." If you leave it at "no", then the
# dates will not be shown.  If you set it to "yes," then the dates
# will show up on the entries. **CHANGE** this to 
# $show_date_submitted = "yes"; 
# if you would like the dates of the submissions to show up.

$show_date_submitted = "no";

# $link_email_address tells the program whether or not to put a link
# to the contributor's email address near their submission.  By default,
# the program will put a link to the person's email address on the
# page.  However, since many people are concerned about receiving
# unsolicited email, you may **CHANGE** this to:
# $link_email_address = "no"; 
# and the email address will not be shown.

$link_email_address = "no";

# If you are using MakeBook as an ongoing story, you might not want
# the names or email addresses of the submittors to show up, as it
# could interrrupt the "flow" of the story.  If you set 
# $hide_authors_names = "yes"; then it will put the authors' names
# into HTML comment format.  This means that you will be able to 
# see them ONLY if you view the source code of the bookfile, but
# they will not show up when viewing the page normally in a web
# browser.  **CHANGE** this to:
# $hide_authors_names = "yes";
# if you wish to have the entries unbroken by the name, email address,
# and date of the submission.

$hide_authors_names = "no";

# $line_between_submissions tells MakeBook whether or not you want
# a line (<hr>) in between entries.  If you **CHANGE**    
# $line_between_submissions = "no"; to 
# $line_between_submissions = "yes"; 
# Then it will put that line in. Otherwise, it will not.

$line_between_submissions = "no";

# $submission_length tells MakeBook whether or not you want
# to limit what people enter to a certain length, or number of
# characters.  If you **CHANGE** $submission_length = "unlimited"; to
# $submission_length = "25"; then users may only enter a maximum of
# 25 characters (including spaces) in their entry.  You can make this
# any number you want, for example:
# $submission_length = "500";
# $submission_length = "42";
# $submission_length = "225";
# For anything other than "unlimited", MakeBook will display an error
# message to the user if he or she enters something longer, and will
# not post their entry until they shorten it.

$submission_length = "500";

# $mail_me_the_submissions tells the program whether or not to
# email you a copy of each submission to the "book."  If you leave
# it at $mail_me_the_submissions = "no"; then it will just add to
# the "book" and will not notify you.  If you **CHANGE** it to
# $mail_me_the_submissions = "yes"; 
# then you will be sent a copy of each submission so that you 
# can remove inappropriate ones.

$mail_me_the_submissions = "yes";

###################################################################
#                                                                 #
#                  Operating System Specific Stuff                #
#                      (Windows vs. Unix/Linux)                   #
#                                                                 #
###################################################################

# In this section, we're going to try to get some data that will
# help us run this script whether you're using Windows NT/95/98 as
# a web server, or a Unix/Linux-based web server.  Here, I feel
# it necessary to point out that Unix/Linux web servers tend to
# be much more flexible and robust (in my experience) than Windows
# ones.  However, if you're stuck with Windows, we'll try to get
# this working anyway. :)

# If your web server is Linux/Unix based, please set
# $opsys below to "unix" like this and go to the Unix/Linux Stuff
# Section below:
# $opsys = "unix";
# Otherwise, if it is a Windows-based platform, set $opsys to "win"
# like this and go to the Windows Stuff section:
# $opsys = "win";

$opsys = "unix";

###################################################################
#                                                                 #
#                  Unix/Linux Stuff                               #
#                                                                 #
###################################################################
# $path_to_sendmail needs to be the FULL path to sendmail on your
# server, and the name of the sendmail file itself:  You will
# probably be able to use what I have below, but sendmail
# is sometimes located in /usr/ucblib instead of /usr/lib and
# may be somewhere else altogether.  Ask your systems administrator
# where sendmail is, just to make sure, then **CHANGE** this to
# the correct path.  Note: on some systems, this is something
# totally different without the word "sendmail" at all such as
# "/var/qmail/bin/qmail-inject".

$path_to_sendmail = "/usr/sbin/sendmail";

###################################################################
#                                                                 #
#                     Windows Stuff                               #
#                                                                 #
###################################################################

# $mail_server_hostname needs to be the hostname of a mail server
# that your web server is allowed to send mail through. Generally,
# this will be something like "mail.yourdomain.com" but it may
# be something completely different, and you may not be able to
# use this at all.  If your web server is also a mail server,
# you may be able to use "localhost" (yes, just that one word,
# no ".com" or anything -- it's a special word that means "this
# machine.")  You will need to ask your local technical support
# people for your website what hostname to use for your outgoing
# mail server, then **CHANGE** this to reflect that. For example:
# $mail_server_hostname = "mail.yourdomain.com";

$mail_server_hostname = "mail.yourdomain.com";

# $this_server_hostname needs to be the hostname of your web
# server where this script will be run.  Sometimes, just the
# "www.yourdomain.com" will work, and sometimes your web
# server has its own name like "web-01.nt.somedomain.com".
# Again, you will need to get the hostname of this machine
# from the technical support people for your web server,
# and **CHANGE** this to reflect what they say. For example:
# $this_server_hostname = "www.yourdomain.com";

$this_server_hostname = "www.yourdomain.com";

#########################################################################
#									#
#            END SECTION WHERE YOU NEED TO CHANGE THINGS		#
#									#
#  You should not need to change anything beyond this point, unless	#
#  you know quite a bit about Perl and are making specific changes	#
#  to the code.								#
#									#
#########################################################################

# Set up some stuff that most CGI programs need...
# Output buffering
   $| = 1;
# Print the "content-type" header so the server and the browser knows
# to display HTML
   print "Content-type: text/html\n\n";  
# Grab whatever was entered into the form.
   %data = &get_data();		

# If you remove this link, without replacing it with a similar
# HTML comment (as above in the License section) you are in violation
# of the license for this program. No, I don't have the resources to
# enforce this, and I know that some people will remove it anyway.
# But honestly, since you didn't have to pay for this, is the link
# really too much to ask? :)

$footer = "$footer";

&debug("<b>IMPORTANT:</b> Be sure to set \$debugging to 0 when this script
       is working. If you have having problems, please copy all of this
       debugging info into an email and send it to me along with a detailed
       explanation of what you were doing to get the error.");
foreach $key (keys(%ENV)){
  &debug("$key $ENV{$key}");
  }

# Now we assign some variables:  whatever is in "" marks must correspond
# to a name="(something)" tag in one of your form fields.  You should
# not have to modify this unless you change the input fields on the
# form.
$name =$data{"Name"};
$email =$data{"Email"};
$text =$data{"Text"};
$text =~ s/</&lt;/g;
$text =~ s/>/&gt;/g;
$date = &get_date();

if($submission_length ne "unlimited"){&check_length;}

# Okay, now, if they set "$use_form_as_bookfile" to yes, then
# we're going to try to get the name of that form. This is usually
# sent by the browser as an "environment" variable called
# "HTTP_REFERER", but that is a URL, so we need to get rid
# of the "http://" and so forth to get the actual filename.

if($use_form_as_bookfile eq "yes"){
   if($ENV{'HTTP_REFERER'} ne ""){ 
      $bookfile = $ENV{'HTTP_REFERER'};
      (@stuff) = split(/\//, $bookfile);
      $filepath =~ s/\/$//;
      if(-f "$filepath/$stuff[$#stuff]"){
         $bookfile = "$filepath/$stuff[$#stuff]";
         $bookfile_url = $ENV{'HTTP_REFERER'};
         &debug("Using $filepath/$stuff[$#stuff] as bookfile.");
	 }
      else {
         &debug("Error: MakeBook would try to add entries to $filepath/$stuff[$#stuff] but it can't find that file.");
	 }
    }
}

# Run the "check_email" subroutine.  This helps to weed out messages
# from people who don't enter a correct email address, for example,
# they leave out an "@" sign, or they just put in a local-type
# address like "bob@bobsite".  The minimum email address we will accept
# is something like "x@x.xx".

&check_email;

# If they forget to enter their name OR email address or both,
# send them a page with the following HTML stuff. The variable
# $ENV{'HTTP_REFERER'} takes them to the page they're accessing
# this form from so they can go back if necessary.  This message
# says what they need to do and gives them the opportunity
# to try again.  If I didn't care if one was missing, then
# I'd make it "if($name eq "" && $email eq ""){" etc.  In Perl,
# && means "and," and || means "or."  You can put any HTML code
# after the word "print", but all " marks and @ signs must be
# preceded by a backslash. (\)

if($name eq "" || $email eq ""){ 

   print "$header<h2>Error: Cannot Process Your Submission!</h2><P>You 
          need to enter your name and e-mail address.
          <p><a onClick=\"javascript:history.back();\"
	  href=\"$ENV{'HTTP_REFERER'}\">Click 
          here to try again</a>$footer";}

# On the other hand, if they entered their name and address but forgot
# to put any text in, the below text will be sent to them with a 
# slightly different message.

elsif($text eq ""){

    print "$header<h2>Error: Cannot Process Your Submission!</h2><P> You need
           to enter some text in the text field.
           <p><a onClick=\"javascript:history.back();\"
	   href=\"$ENV{'HTTP_REFERER'}\">Click 
           here to try again</a> $footer";}

# If they get past the "if" and the "elsif" watchdogs, then let's 
# go ahead and send the mail.

else{

# The subroutine "send_mail" sends you email with the submission if
# you have chosen that option above.

if($mail_me_the_submissions =~ /yes/i){
   &mail_owner;
   }

# The subroutine "write_to_bookfile" adds the entry to the bookfile.

   &write_to_bookfile;

# Print out a confirmation message and return it to the
# person. Again, you can put any HTML code relevant to your
# site in this message after the word "print" but you MUST
# put a \ before any "s, or @s or the program will get
# confused.  And that's all she wrote!

print "$header  
	<a href=\"$ENV{'HTTP_REFERER'}\"></a>.";

}

sub check_email

  {

  if($email !~ /(.{1,})(\@)(.{1,})(\.)(.{2,})/ || $email =~ /\@.*\@/ ||
     $email =~ /\.$/)
   {
  print "$header<h2>Error: Incorrect email address</h2></center><P>	\n
	Sorry, you didn't enter a proper email address.  Your \n
	address must consist of \"yourlogin\@yourhost.yourdomain.\"\n
	If you're getting this message, you may have forgotten the\n
	\"\@\" sign in your email address, or you may have left off\n
	part of the address.  <P>\n
	You entered: $email <P>\n
	If this is incorrect, please <a onClick=\"javascript:history.back();\"
	href=\"$ENV{HTTP_REFERER}\">
	go back to the form and enter your email address again.</a>
        $footer";
 	exit();
   }
}


sub mail_owner {

   &send_mail($owner,$owner,$email,$name,
         $email,$name,"where have gerald go?",
         $text,$mail_server_hostname,$this_server_hostname,$opsys,
	 $htmlmail);
}


sub write_to_bookfile {

# Okay, now, we're going to open up our book file and append this to 
# it.  IMPORTANT:  this depends on your having put the <!-- MAKEBOOK START -->
# and <!-- MAKEBOOK STOP --> tags in the html file so that it can find 
# where to put the new entries.

# First, get the whole contents of the file so we can get rid of the
# footer temporarily...

  if(-f "$bookfile"){
  undef $/;
  open(FILE, "+<$bookfile") 
   || &debug("Oops, I cannot read the bookfile $bookfile: $!");
  if($opsys eq "unix"){flock(FILE, 2);}
  else{binmode(FILE);}
     $bookfile_contents = <FILE>;
  $/ = "\n";

# Then, we want to put in a line in the text that says who the 
# contribution came from with a link to their email address, if
# desired. We'll also see if we should print the date of the 
# submission, and whether we should just hide the names altogether.

if($line_between_submissions eq "yes"){ $br = "<hr>";}
else {$br = "<br>";}

if($link_email_address =~ /no/i){
  
  $text = "\n\n\n<TR><td bgcolor=\"#ffff33\"><font color=\"black\">$text</font></TD>\n  <td bgcolor=\"#99cc99\">$name</TD></TR>";
  }
else{
  $text = "\n\n$br(Submitted by <a href=mailto:$email>$name</a>)<P>\n$text<P>\n";
  }
if($show_date_submitted =~ /yes/i){

  $text =~ s/Submitted/Submitted $date/;
  }

if($hide_authors_names =~ /yes/i){

  $text =~ s/\(Submitted/<!-- Submitted/;
  $text =~ s/\)/ -->/;
  $text =~ s/<a href=mailto://;
  $text =~ s/$email>/$email /; $text =~ s/<\/a>/ /;
  }

# Make sure there is an appropriate header and footer...

($top,$contents,$bottom) = split(/<!-- MAKEBOOK .*? -->/, $bookfile_contents);

# Now, we remove the footer from the bookfile contents so we can stick
# the new text in there.

if($add_to_end_of_file =~ /yes/i){
  $bookfile_contents = "$top<!-- MAKEBOOK TEXT START -->$contents$text<!-- MAKEBOOK TEXT END -->$bottom";
  }
elsif($add_to_end_of_file =~ /no/i){
  $bookfile_contents = "$top<!-- MAKEBOOK TEXT START -->$text$contents<!-- MAKEBOOK TEXT END -->$bottom";
  } 

# Okay.  Now we just open up the bookfile for writing, print the 
# new bookfile contents to the file and close up the file.

  truncate(FILE, length($bookfile_contents));
  seek(FILE, 0, 0);
  print FILE "$bookfile_contents";
  close(FILE);
  }
  else {
    print "$header
	   Error: could not find $bookfile to add entry. Please
	   <a href=\"mailto:$owner_email\">notify the administrator</a>.
	   $footer";
    exit();
    }
}


sub get_date {

   @months = ('January','February','March','April','May','June','July',
              'August','September','October','November','December');

   ($sec,$min,$hour,$mday,$mon,$year) = (localtime(time))[0,1,2,3,4,5];
   $min = sprintf("%0.2d", $min);
   $sec = sprintf("%0.2d", $sec);
   $hour = sprintf("%0.2d", $hour);
   $year += 1900;

   $date = "$months[$mon] $mday, $year $hour\:$min\:$sec";
   $date;

}

sub debug {

 if($debugging == 1){
    print "DEBUGGING INFO: $_[0] <br>";
    }
}
sub get_data {
    local($string);

    # get data
    if ($ENV{'REQUEST_METHOD'} eq 'GET') {
        $string = $ENV{'QUERY_STRING'};
    }				
    else { read(STDIN, $string, $ENV{'CONTENT_LENGTH'}); }

    # split data into name=value pairs
    @data = split(/&/, $string);
   
    # split into name=value pairs in associative array
    foreach (@data) {
	split(/=/, $_);
	$_[0] =~ s/\+/ /g; # plus to space
	$_[0] =~ s/%00//g; # We don' need no steenking nulls :)
        $_[0] =~ s/%0a/newline/g;
	$_[0] =~ s/%(..)/pack("c", hex($1))/ge; # hex to alphanumeric
	if(defined($data{$_[0]})){ # In case we have checkboxes. :-)
	   $data{$_[0]} .= "\0";
	   $data{$_[0]} .= "$_[1]";
	   }
	else {
	$data{"$_[0]"} = $_[1];
	  }
    }
    # translate special characters
    foreach (keys %data) {
	$data{"$_"} =~ s/\+/ /g; # plus to space
	$data{"$_"} =~ s/%00//g; # We don' need no steenking nulls :)
        $data{"$_"} =~ s/%0a/newline/g;
	$data{"$_"} =~ s/%(..)/pack("c", hex($1))/ge; # hex to alphanumeric
    }

    %data;			# return associative array of name=value
}

sub send_mail {

   local($toemail,$toname,$fromemail,$fromname,
         $replytoemail,$replytoname,$subject,
         $message,$mail_server_hostname,$this_server_hostname,$opsys,
	 $htmlmail) = @_;

  &debug("Attempting to send message \"$subject\" to $toemail");
  my($boundary) = crypt("blah",time.$$).time.$$;

if($opsys eq "win"){
   my($port,$them,$child,$sockaddr,$hostname,$name,$aliases,$proto,
      $type,$len,$thisaddr,$thataddr);
   $port = 25;
   $them = "$mail_server_hostname";
   $AF_INET = 2; $SOCK_STREAM = 1;

   $SIG{'INT'} = 'dokill';
   sub dokill {
       kill 9,$child if $child;
   }

   $sockaddr = 'S n a4 x8';

   $hostname = "$this_server_hostname";

   ($name,$aliases,$proto) = getprotobyname('tcp');
   ($name,$aliases,$port) = getservbyname($port,'tcp')
       unless $port =~ /^\d+$/;;
   ($name,$aliases,$type,$len,$thisaddr) =
        gethostbyname($hostname);
   ($name,$aliases,$type,$len,$thataddr) = gethostbyname($them);

   $this = pack($sockaddr, $AF_INET, 0, $thisaddr);
   $that = pack($sockaddr, $AF_INET, $port, $thataddr);

   if (socket(S, $AF_INET, $SOCK_STREAM, $proto)) {
   }
   else { &debug("Could not create socket for mail: $!"); }

   if (bind(S, $this)) {
   }
   else { &debug("Could not bind to socket (this may be okay anyway): $!"); }

   if (connect(S,$that)) {
   }
    else { &debug("Could not connect to socket: $!"); }

   select(S); $| = 1; select(STDOUT);

   $a=<S>; 
   print S "HELO $this_server_hostname\n";
   $a=<S>;  &debug("Mail server responded: $a");
   print S "MAIL FROM:<$fromemail>\r\n";
   $a=<S>;  &debug("Mail server responded: $a");
   print S "RCPT TO:<$toemail>\r\n";
   $a=<S>;  &debug("Mail server responded: $a");
   print S "DATA \r\n";
   $a=<S>;  &debug("Mail server responded: $a");
   print S "To: $toname <$toemail>\n";
   print S "From: $fromname <$fromemail>\n";
   if($replytoemail ne ""){
      print S "Reply-to: $replytoname <$replytoemail>\n";
      }
   print S "Subject: $subject\n";
   if($htmlmail eq "yes"){ 
     print S "MIME-Version: 1.0\n";
     print S "Content-type: MULTIPART/MIXED; BOUNDARY=\"$boundary\"\n";
     print S "--$boundary\n";
     print S "Content-type: text/html;\n\n";
     print S "$message\n";
     print S "\n\n";
     print S "--$boundary\n";
     print S "Content-type: TEXT/PLAIN; charset=US-ASCII\n\n";
     print S "$message--$boundary--\n";
     }
   else {
      print S "\n"; 
      print S "$message\n";
      }
   print S ".\n";
   $a=<S>; &debug("Mail server responded: $a");
   print S "QUIT";
   &debug("Sending mail done.");

   }

elsif($opsys eq "unix"){

   # Allow for qmail-inject ~sigh~
   # Most other mailer thingies do use the -t option like
   # sendmail in order to be compatible, but apparently
   # qmail-inject does not. Oh well...

   if($path_to_sendmail !~ /qmail-inject/){
      $path_to_sendmail = "$path_to_sendmail -t";
      }

   open(MAIL, "|$path_to_sendmail") || 
     &debug("Could not open sendmail: $!");
     print MAIL "To: \"$toname\" <$toemail>\n";
     print MAIL "From: \"$fromname\" <$fromemail>\n";
     if($replytoemail ne ""){
       print MAIL "Reply-to: \"$replytoname\" <$replytoemail>\n";
       }
     print MAIL "Subject: $subject\n";
     if($htmlmail eq "yes"){ 
        print MAIL "MIME-Version: 1.0\n";
        print MAIL "Content-type: MULTIPART/MIXED; BOUNDARY=\"$boundary\"\n";
        print MAIL "--$boundary\n";
        print MAIL "Content-type: text/html;\n\n";
        print MAIL "$message\n";
        print MAIL "\n\n";
        print MAIL "--$boundary\n";
        print MAIL "Content-type: TEXT/PLAIN; charset=US-ASCII\n\n";
        print MAIL "$message--$boundary--\n";
        }
     else {
        print MAIL "\n"; 
        print MAIL "$message\n";
        }
     close(MAIL) || &debug("Sending mail got an error: $! $?");
     &debug("Sending mail done.");
   }

else {

   &debug("Cannot send mail. '$opsys' is not a valid operating sytem.
           Please set \$opsys to either 'unix' or 'win' in the script
           and try this again.");
    }
}


sub check_length {
 
 my $len = length($data{'Text'});
 if($len > $submission_length){
    print "$header<h2>Error: Cannot Process Your Submission!</h2><P> 
	   Sorry, but entries are limited to a length of $submission_length
	   characters. You have entered $len characters. Please 
           <a onClick=\"javascript:history.back();\"
	   href=\"$ENV{'HTTP_REFERER'}\">Click 
           here to go back and shorten your entry.</a> $footer";
     exit();
     }

}
